### ISSUE TITLE
PRACTICA BIZAGI PROYECTO

### ISSUE THREAD

**Issue by YaelStO** [SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-proyecto-equipo-jdgras#1]
[REPORTE DE PRACTICA 6.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-proyecto-equipo-jdgras/files/12855406/REPORTE.DE.PRACTICA.6.pdf)

**Comment by ka194** [comment]
18/20  Buen trabajo

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
